{
  pkgs,
  lib,
  username,
  activeTheme,
  ...
}:

let
  extractToClipboard = pkgs.writeShellScriptBin "txt-extr" ''
    hyprshot -m region --raw | tesseract stdin stdout | wl-copy
  '';
  cursors = {
    "catppuccin-mocha" = "Catppuccin Mocha Mauve";
    "catppuccin-frappe" = "Catppuccin Frappé Dark";
    "gruvbox-dark" = "Capitaine Cursors (Gruvbox)";
  };
in
{
  imports = [
    ./common-wayland.nix
    ../features/kitty.nix
    ../features/waybar.nix
    ../features/fuzzel.nix
    ../features/hyprpaper.nix
  ];

  environment.sessionVariables = {
    HYPRCURSOR_THEME = cursors."${activeTheme.name}" or "Bibata-Modern-Ice";
    XCURSOR_THEME = cursors."${activeTheme.name}" or "Bibata-Modern-Ice";
    GDK_SCALE = "1";
    HYPRCURSOR_SIZE = "24";
    XCURSOR_SIZE = "24";
  };

  services.displayManager.defaultSession = "hyprland";
  services.logind.settings.Login.HandleLidSwitch = "ignore";
  services.logind.settings.Login.HandlePowerKey = "suspend";

  security.pam.services.hyprland = {
    text = ''
      auth       optional    pam_gnome_keyring.so
      session    optional    pam_gnome_keyring.so auto_start
    '';
  };
  security.pam.services."system-local-login".text = ''
    auth       optional    pam_gnome_keyring.so
    session    optional    pam_gnome_keyring.so auto_start
  '';
  security.pam.services."gdm-password".text = ''
    auth       optional    pam_gnome_keyring.so
    session    optional    pam_gnome_keyring.so auto_start
  '';
  programs.hyprland = {
    enable = true;
    # # set the flake package
    # package = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.hyprland;
    # # make sure to also set the portal package, so that they are in sync
    # portalPackage = inputs.hyprland.packages.${pkgs.stdenv.hostPlatform.system}.xdg-desktop-portal-hyprland;

    # # withUWSM = true;
    xwayland.enable = true;
  };

  # nix.settings = {
  #   substituters = ["https://hyprland.cachix.org"];
  #   trusted-public-keys = ["hyprland.cachix.org-1:a7pgxzMz7+chwVL3/pzj6jIBMioiJM7ypFP8PwtkuGc="];
  # };

  # programs.uwsm.enable = true;

  boot.extraModprobeConfig = ''
    options i915 mitigations=off
  '';

  home-manager.users.${username} = {
    home.packages = [
      pkgs.swaynotificationcenter
      pkgs.hyprpolkitagent
      pkgs.hyprlock
      pkgs.waybar

      pkgs.nemo
      pkgs.nautilus
      # pkgs.kdePackages.dolphin

      pkgs.hyprshot
      pkgs.hyprpicker
      pkgs.swaynotificationcenter
      pkgs.hyprlock
      # pkgs.hypridle # probably wont end up using it
      # pkgs.pavucontrol
      pkgs.pamixer
      pkgs.swappy
      pkgs.playerctl
      pkgs.brightnessctl
      pkgs.pulsemixer
      pkgs.catppuccin-cursors.mochaMauve
      pkgs.catppuccin-cursors.frappeDark
      pkgs.nwg-look
      pkgs.dconf-editor
      pkgs.banana-cursor
      pkgs.bibata-cursors
      pkgs.tesseract
      pkgs.capitaine-cursors-themed
    ];
    home.file.".config/hypr/hyprland.conf" = {
      force = true;
      text = ''
        # #######################################################################################
        # AUTOGENERATED HYPR CONFIG.
        # PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hypr.conf AND EDIT IT,
        # OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.
        # #######################################################################################

        # autogenerated = 1 # remove this line to remove the warning

        # This is an example Hyprland config file.
        # Refer to the wiki for more information.
        # https://wiki.hyprland.org/Configuring/Configuring-Hyprland/

        # Please note not all available settings / options are set here.
        # For a full list, see the wiki

        # You can split this configuration into multiple files
        # Create your files separately and then link them to this file like this:
        # source = ~/.config/hypr/myColors.conf


        ################
        ### MONITORS ###
        ################

        # See https://wiki.hyprland.org/Configuring/Monitors/
        monitor=eDP-2,2560x1600@165,2560x0,1 # internal when dGPU
        monitor=eDP-1,2560x1600@165,2560x0,1
        monitor=DP-2,2560x1440@165,0x0,1 # samsung curved
        monitor=DP-3,2560x1440@165,0x0,1 # samsung curved
        # monitor=DP-3,4096x2160@60,-4096x0,1.6 # barbs
        monitor=DP-4,1920x1080@60,0x1600,1

        bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off eDP-2
        bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on eDP-2
        bindl = , switch:on:Lid Switch, exec, hyprctl dispatch dpms off eDP-1
        bindl = , switch:off:Lid Switch, exec, hyprctl dispatch dpms on eDP-1

        # # trigger when the switch is turning on
        # bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
        # #bindl = , CTRL + ALT + SHIFT + $mainMod, E, exec, hyprctl keyword monitor "eDP-1, disable"
        # # trigger when the switch is turning off
        # bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 2560x1600, 0x0, 1" && wayvnc && hyprpaper &

        ###################
        ### MY PROGRAMS ###
        ###################

        # See https://wiki.hyprland.org/Configuring/Keywords/

        # Set programs that you use
        $terminal = kitty
        $fileManager = nautilus
        $browser = microsoft-edge --profile-directory="Profile 12"
        $school_browser = zen -p nouveau --new-tab https://salc124.github.io/ # firefox # microsoft-edge --profile-directory="Profile 13" --new-window salc124.github.io
        $launcher = fuzzel

        #################
        ### AUTOSTART ###
        #################

        # Autostart necessary processes (like notifications daemons, status bars, etc.)
        # Or execute your favorite apps at launch like this:
        #exec-once = kitty --class floating --hold sh -c "echo you are a f##cking charlatan."
        # exec-once = nm-applet &
        # exec-once = waybar & microsoft-edge & hyprpaper
        #
        # exec-once = bash ~/.config/hypr/start.sh
        exec-once = hyprpaper
        exec-once = waybar
        exec-once = swaync
        exec-once = nm-applet
        exec-once = syncthing
        exec-once = syncthingtray --wait
        exec-once = corectrl

        # exec-once = wayvnc -f 30

        # exec-once = systemctl --user start hyprpolkitagent
        exec-once = systemctl --user enable --now hyprpolkitagent.service

        exec-once = zellij da -y
        exec-once = zellij -s home

        # fix stupid themes
        # exec-once = dconf write /org/gnome/desktop/interface/gtk-theme "'Adwaita'"
        # exec-once = dconf write /org/gnome/desktop/interface/icon-theme "'Flat-Remix-Red-Dark'"
        # exec-once = dconf write /org/gnome/desktop/interface/document-font-name "'Noto Sans Medium 11'"
        # exec-once = dconf write /org/gnome/desktop/interface/font-name "'Noto Sans Medium 11'"
        # exec-once = dconf write /org/gnome/desktop/interface/monospace-font-name "'Noto Sans Mono Medium 11'"

        # fix sceenshrare
        exec-once = dbus-update-activation-environment --systemd --all
        exec-once = systemctl --user import-environment QT_QPA_PLATFORMTHEME

        # microsoft-edge is default
        exec-once = xdg-settings set default-web-browser microsoft-edge.desktop
        debug:disable_logs = false

        #############################
        ### ENVIRONMENT VARIABLES ###
        #############################

        # See https://wiki.hyprland.org/Configuring/Environment-variables/



        #####################
        ### LOOK AND FEEL ###
        #####################

        # Refer to https://wiki.hyprland.org/Configuring/Variables/

        # https://wiki.hyprland.org/Configuring/Variables/#general
        general {
            gaps_in = ${if activeTheme.name == "frutiger-aero" then "16" else "4"}
            gaps_out = ${if activeTheme.name == "frutiger-aero" then "32" else "8"}

            border_size = ${if activeTheme.name == "frutiger-aero" then "4" else "4"}

            # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
            col.active_border = rgba(${builtins.substring 1 6 activeTheme.base0E}ff) # rgba(B4BEFEee) 45deg
            col.inactive_border = rgba(${builtins.substring 1 6 activeTheme.base03}FF)

            # Set to true enable resizing windows by clicking and dragging on borders and gaps
            resize_on_border = true

            # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
            allow_tearing = false

            layout = dwindle

            snap {
                enabled = false
                window_gap = 25
                monitor_gap = 25
                border_overlap = false
            }
        }


        # https://wiki.hyprland.org/Configuring/Variables/#decoration
        decoration {
            rounding = ${if activeTheme.name == "frutiger-aero" then "0" else "8"}

            # Change transparency of focused and unfocused windows
            ${lib.optionalString (activeTheme.name == "frutiger-aero") ''
              active_opacity = .65
              inactive_opacity = .65
            ''}
            ${lib.optionalString
              (activeTheme.name == "catppuccin-mocha" || activeTheme.name == "cherry-blossom")
              ''
                active_opacity = 1.0 # 0.85
                inactive_opacity = 1.0 # 0.85
              ''
            }

            shadow {
                enabled = ${if activeTheme.name == "frutiger-aero" then "true" else "false"}
                range = 2
                sharp = false
                offset = 28 28
                color = rgba(1C1C2AFF)
            }

            # drop_shadow = true
            # shadow_range = 4
            # shadow_render_power = 3
            # col.shadow = rgba(${builtins.substring 1 6 activeTheme.base0D}ee)

            # https://wiki.hyprland.org/Configuring/Variables/#blur
            blur {
                enabled = true
                size = 3
                passes = 3 # 5
                new_optimizations = true
                # noise = 0.25

                vibrancy = 0.1 # 0.1696
            }
            # windowrule = noblur,class:^(microsoft-edge)$
            # windowrule = opacity 1 override 1 override 1,class:^(microsoft-edge)$

            # windowrule = noblur,class:^(vesktop)$
            # windowrule = opacity 1 override 1 override 1,class:^(vesktop)$
            #
            # windowrule = noblur,class:^(obsidian)$
            # windowrule = opacity 1 override 1 override 1,class:^(obsidian)$
        }

        # https://wiki.hyprland.org/Configuring/Variables/#animations
        animations {
            enabled = true

            # Default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
            bezier = instant, 0.0, 0.0, 1.0, 1.0

            animation = windows, 1, 1, instant
            animation = windowsIn, 1, 1, instant
            animation = windowsOut, 1, 1, instant
            animation = border, 1, 1, instant
            animation = borderangle, 1, 1, instant
            animation = fade, 1, 1, instant
            animation = workspaces, 1, 1, instant


            #bezier = myBezier, 0.05, 0.9, 0.1, 1.05

            #animation = windows, 1, 7, myBezier
            #animation = windowsOut, 1, 7, default, popin 80%
            #animation = border, 1, 10, default
            #animation = borderangle, 1, 8, default
            #animation = fade, 1, 7, default
            #animation = workspaces, 1, 6, default

            # bezier = myBezier, 1.05, 0.9, 0.1, 1.05
            #
            # animation = windows, 1, 7, myBezier
            # animation = windowsIn, 1, 7, default, gnomed
            # animation = windowsOut, 1, 7, default, gnomed
            # animation = border, 1, 10, default
            # animation = borderangle, 1, 8, default
            # animation = fade, 1, 7, myBezier
            # animation = workspaces, 1, 6, default
        }

        # See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        dwindle {
            pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
            preserve_split = true # You probably want this
            smart_split = true
        }

        # See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        # master {
        #     new_is_master = true
        # }

        # https://wiki.hyprland.org/Configuring/Variables/#misc
        misc {
            force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
            disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
        }


        #############
        ### INPUT ###
        #############

        # https://wiki.hyprland.org/Configuring/Variables/#input
        input {
            kb_layout = us
            kb_variant =
            kb_model =
            kb_options =
            kb_rules =

            follow_mouse = 1

            sensitivity = 0.75 # -1.0 - 1.0, 0 means no modification.

            touchpad {
                natural_scroll = true
        	      tap-and-drag = false
                ${
                  # clickfinger_behavior = true
                  ""
                }
                disable_while_typing = false
                middle_button_emulation = true
            }
        }

        # https://wiki.hyprland.org/Configuring/Variables/#gestures
        gestures {
            # workspace_swipe = true
            # workspace_swipe_fingers = 3
            gesture = 3, horizontal, workspace # new way to do the above
            workspace_swipe_distance = 900
        }

        # Example per-device config
        # See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more
        device {
            name = epic-mouse-v1
            sensitivity = -0.5
        }


        ####################
        ### KEYBINDINGSS ###
        ####################

        # See https://wiki.hyprland.org/Configuring/Keywords/
        $mainMod = SUPER # Sets "Windows" key as main modifier

        # Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
        bind = $mainMod, Q, exec, $terminal
        bind = $mainMod, C, killactive,
        bind = CTRL + ALT + SHIFT, delete, exit,
        bind = $mainMod, E, exec, $fileManager
        bind = $mainMod, V, togglefloating,
        bind = $mainMod, SPACE, exec, $launcher
        bind = $mainMod, P, pseudo, # dwindle
        bind = $mainMod, X, togglesplit, # dwindle
        bind = $mainMod, B, exec, $browser
        bind = $mainMod, F, fullscreen
        bind = $mainMod, A, exec, kitty --class floating
        bind = $mainMod, Z, exec, $school_browser
        bind = $mainMod, O, exec, obsidian

        # screenshot
        bind = , Print, exec, hyprshot -m region -o ~/Pictures/Screenshots/ -z
        bind = shift, Print, exec, hyprshot -m window -o ~/Pictures/Screenshots/ -z
        bind = ctrl, Print, exec, hyprshot -m output -m eDP-2 -o ~/Pictures/Screenshots/ -z

        # extract text
        bind = $mainMod SHIFT, t, exec, ${lib.getExe extractToClipboard}

        # lock screen
        bind = $SUPER_SHIFT alt, l, exec, hyprlock

        # audio controls
        bindl = , XF86AudioPlay, exec, playerctl -p spotify play-pause
        bindl = , XF86AudioPrev, exec, playerctl -p spotify previous
        bindl = , XF86AudioNext, exec, playerctl -p spotify next

        bindl = , XF86AudioMute, exec, pamixer --toggle-mute --allow-boost
        binde = , XF86AudioLowerVolume, exec, pamixer --decrease 5 --allow-boost
        binde = , XF86AudioRaiseVolume, exec, pamixer --increase 5 --allow-boost

        # Move focus with mainMod + arrow keys
        bind = $mainMod, h, movefocus, l
        bind = $mainMod, l, movefocus, r
        bind = $mainMod, k, movefocus, u
        bind = $mainMod, j, movefocus, d

        # Switch workspaces with mainMod + [0-9]
        bind = $mainMod, 1, workspace, 1
        bind = $mainMod, 2, workspace, 2
        bind = $mainMod, 3, workspace, 3
        bind = $mainMod, 4, workspace, 4
        bind = $mainMod, 5, workspace, 5
        bind = $mainMod, 6, workspace, 6
        bind = $mainMod, 7, workspace, 7
        bind = $mainMod, 8, workspace, 8
        bind = $mainMod, 9, workspace, 9
        bind = $mainMod, 0, workspace, 10

        # Move active window to a workspace with mainMod + SHIFT + [0-9]
        bind = $mainMod SHIFT, 1, movetoworkspace, 1
        bind = $mainMod SHIFT, 2, movetoworkspace, 2
        bind = $mainMod SHIFT, 3, movetoworkspace, 3
        bind = $mainMod SHIFT, 4, movetoworkspace, 4
        bind = $mainMod SHIFT, 5, movetoworkspace, 5
        bind = $mainMod SHIFT, 6, movetoworkspace, 6
        bind = $mainMod SHIFT, 7, movetoworkspace, 7
        bind = $mainMod SHIFT, 8, movetoworkspace, 8
        bind = $mainMod SHIFT, 9, movetoworkspace, 9
        bind = $mainMod SHIFT, 0, movetoworkspace, 10

        bind = $mainMod&Shift&Ctrl, 1, movetoworkspacesilent, 1
        bind = $mainMod&SHIFT&Ctrl, 2, movetoworkspacesilent, 2
        bind = $mainMod&SHIFT&Ctrl, 3, movetoworkspacesilent, 3
        bind = $mainMod&SHIFT&Ctrl, 4, movetoworkspacesilent, 4
        bind = $mainMod&SHIFT&Ctrl, 5, movetoworkspacesilent, 5
        bind = $mainMod&SHIFT&Ctrl, 6, movetoworkspacesilent, 6
        bind = $mainMod&SHIFT&Ctrl, 7, movetoworkspacesilent, 7
        bind = $mainMod&SHIFT&Ctrl, 8, movetoworkspacesilent, 8
        bind = $mainMod&SHIFT&Ctrl, 9, movetoworkspacesilent, 9
        bind = $mainMod&SHIFT&Ctrl, 0, movetoworkspacesilent, 10

        bind = $SUPER_SHIFT, h, movewindow, l
        bind = $SUPER_SHIFT, j, movewindow, d
        bind = $SUPER_SHIFT, k, movewindow, u
        bind = $SUPER_SHIFT, l, movewindow, r


        # Example special workspace (scratchpad)
        bind = $mainMod, S, togglespecialworkspace, magic
        bind = $mainMod&SHIFT&CTRL, S, movetoworkspacesilent, special:magic
        bind = $mainMod SHIFT, S, movetoworkspace, special:magic

        bind = $mainMod, D, togglespecialworkspace, magicTwo
        bind = $mainMod&SHIFT&CTRL, D, movetoworkspacesilent, special:magicTwo
        bind = $mainMod SHIFT, D, movetoworkspace, special:magicTwo

        # Scroll through existing workspaces with mainMod + scroll
        bind = $mainMod, mouse_down, workspace, e+1
        bind = $mainMod, mouse_up, workspace, e-1

        # Move/resize windows with mainMod + LMB/RMB and dragging
        bindm = $mainMod, mouse:272, movewindow
        bindm = $mainMod, mouse:273, resizewindow

        # brightness
        # bind = , code:232, exec, brightnessctl --device=amdgpu_bl2 s 10%- # amdgpu_bl2 for dGPU (for both)
        # bind = , code:233, exec, brightnessctl --device=amdgpu_bl2 s +10%
        bind = , code:232, exec, brightnessctl --device=amdgpu_bl1 s 10%-
        bind = , code:233, exec, brightnessctl --device=amdgpu_bl1 s +10%
        bind = , code:232, exec, brightnessctl --device=amdgpu_bl2 s 10%-
        bind = , code:233, exec, brightnessctl --device=amdgpu_bl2 s +10%

        ##############################
        ### WINDOWS AND WORKSPACES ###
        ##############################

        # See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
        # See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

        # Example windowrule v1
        windowrule = float, class:^(wofi)$
        windowrule = float, class:Matplotlib

        windowrule = opacity 100%, class:zen-twilight
        windowrule = noborder, class:zen-twilight
        windowrule = noborder, class:^(Godot)$
        windowrule = tile, class:^(Godot)$
        # windowrule = rounding 0 , class:zen-twilight

        windowrule = opacity 100%, class:steam_app_1229490

        windowrule = opacity 0.86, class:jetbrains-studio
        windowrule = opacity 1, class:^(jetbrains-studio)$,title:^(Running Devices)$
        # windowrule =

        windowrule = float, class:$launcher
        windowrule = float, class:^($fileManager)$
        windowrule = float, class:org.gnome.Nautilus
        # windowrule = tile, class:^(com-cburch-logisim-Main)$ # ts rule is geeked on fent
        windowrule = tile, title:.*Logisim-evolution.*

        windowrule = float, title:^(nmtui)$
        windowrule = size 554 640, title:^(nmtui)$
        windowrule = move 100%-w-30 85, title:^(nmtui)$

        # temp term
        windowrule = float, class:floating
        windowrule = center 1, class:floating
        windowrule = size 798 504, class:floating
        # windowrule = forcergbx, class:floating
        # windowrule = opacity 100%, class:floating



        windowrule = opacity 100%,class:^(Godot)$

        # windowrule = opacity 0.60, class:dev.zed.Zed-Nightly
        windowrule = opacity 1.0 override 1.0 override, class:dev.zed.Zed-Nightly

        windowrule = float, title:^(Sign in - Google Accounts — Zen Twilight)$


        windowrule = suppressevent maximize, class:.* # You'll probably like this.

        # make terminal awesome
        layerrule = blur,class:^(kitty)$,title:^(kitty)$
        # layerrule = dimaround,class:^(kitty)$,title:^(kitty)$
        # layerrule = ignorealpha 0.5,class:^(kitty)$,title:^(kitty)$

        # kicad
        windowrule = float, title:^(Symbol Library Browser)$


        windowrule = float, class:xdg-desktop-portal-gtk

        # -- Fix odd behaviors in IntelliJ IDEs -- https://github.com/fubuki4649/dotfiles/blob/master/.config/hypr/hyprland.conf
        #! Fix focus issues when dialogs are opened or closed
        # windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
        #! Fix splash screen showing in weird places and prevent annoying focus takeovers
        windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
        windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
        windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

        #! Center popups/find windows
        windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
        #! Enabling this makes it impossible to provide input to any popup dialogue (search window, new file, etc.)
        windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
        windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
        #! Disable window flicker when autocomplete or tooltips appear
        windowrulev2 = noinitialfocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1
        # -- End of IntelliJ Rules --

        windowrulev2 = focusonactivate, class:^(MuseScore4)$, title:^(Additional score information)$

        windowrule = float,initialTitle:Claude
        windowrule = size 607 641, initialTitle:Claude

        windowrule = float,initialTitle:Clod
        windowrule = size 607 641, initialTitle:Clod



        exec = pkill waybar; waybar
        exec = pkill hyprpaper; hyprpaper
      '';
    };

  };
}
